package com.luteh.kampusonline.ui.activities.dashboard;

import com.luteh.kampusonline.model.User;

/**
 * Created by Luthfan Maftuh on 14/11/2018.
 * Email luthfanmaftuh@gmail.com
 */
public interface IDashboardActivityPresenter {
    /**
     * Get user profile info
     * @param uid User UID that generated by Firebase Authentication
     */
    void getUserInfo(String uid);

    void getJatuhTempoDate();

    void onDestroy();
}
